### ISSUE TITLE
I am running this app with node - 6.11 and npm - 3.10 ,  gets  error

### ISSUE THREAD

**Issue by sameerparab355** [DanWahlin/Angular-NodeJS-MongoDB-CustomersService#1]
> concurrently "npm run tsc:w" "nodemon server.js"

'concurrently' is not recognized as an internal or external command,
operable program or batch file.

**Comment by DanWahlin** [comment]
I've only seen that error once on a Windows machine (I've never been able to duplicate it though). I'd first delete node_modules and run npm install again.

If it still doesn't work you can try installing concurrently globally (npm install -g concurrently) to potentially work around it on your machine. It's not an error related to the app code and since I've been unable to duplicate the error on Windows there's not much more I can offer there at this point.
